### PR TITLE
Fix warnings for Ansible 2.4; increase minimum supported version

### PR DESCRIPTION
**Pull request by hectcastro**
Remove Jinja2 syntax from `when` statements and include a `requirements.txt` file for installing Ansible, Molecule, and Vagrant support for Molecule.

Ansible 2.4 is now the minimum version of Ansible that is supported for this role.

Resolves https://github.com/azavea/ansible-aws-ena/issues/6

---

**Testing**

- Follow the instructions in the `README` to install Molecule
- Execute `molecule test` from the root of the repository
- Confirm that there are no deprecation warnings in the Ansible/Molecule output

### CODE REVIEW

File: requirements.txt [hunk 1]
```diff
@@ -0,0 +1,2 @@
+molecule==1.25.1
```
Comment (tnation14) [inline requirements.txt]: I couldn't get tests to pass with the version of Testinfra installed by Molecule:

```bash
tnation@walnut:src/ansible-aws-ena % molecule verify                               
--> Executing ansible-lint...
--> Executing flake8 on *.py files found in tests/...
--> Executing testinfra tests found in tests/...
============================= test session starts ==============================
platform darwin -- Python 2.7.10, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /Users/tnation/Documents/projects/src/ansible-aws-ena, inifile:
plugins: testinfra-1.6.3
collected 0 items / 1 errors                                                   

==================================== ERRORS ====================================
______________________ ERROR collecting tests/test_ena.py ______________________
../../../../.venvs/ansible-aws-ena/lib/python2.7/site-packages/pluggy/__init__.py:617: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
../../../../.venvs/ansible-aws-ena/lib/python2.7/site-packages/pluggy/__init__.py:222: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../../.venvs/ansible-aws-ena/lib/python2.7/site-packages/pluggy/__init__.py:216: in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
../../../../.venvs/ansible-aws-ena/lib/python2.7/site-packages/_pytest/python.py:192: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../../.venvs/ansible-aws-ena/lib/python2.7/site-packages/_pytest/python.py:370: in _genfunctions
    self.ihook.pytest_generate_tests(metafunc=metafunc)
../../../../.venvs/ansible-aws-ena/lib/python2.7/site-packages/pluggy/__init__.py:617: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
../../../../.venvs/ansible-aws-ena/lib/python2.7/site-packages/pluggy/__init__.py:222: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../../.venvs/ansible-aws-ena/lib/python2.7/site-packages/pluggy/__init__.py:216: in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
../../../../.venvs/ansible-aws-ena/lib/python2.7/site-packages/testinfra/plugin.py:136: in pytest_generate_tests
    ansible_inventory=metafunc.config.option.ansible_inventory,
../../../../.venvs/ansible-aws-ena/lib/python2.7/site-packages/testinfra/host.py:125: in get_hosts
    for backend in testinfra.backend.get_backends(hosts, **kwargs):
../../../../.venvs/ansible-aws-ena/lib/python2.7/site-packages/testinfra/backend/__init__.py:84: in get_backends
    for name in klass.get_hosts(host, **kw):
../../../../.venvs/ansible-aws-ena/lib/python2.7/site-packages/testinfra/backend/ansible.py:72: in get_hosts
    return AnsibleRunner(kwargs.get("ansible_inventory")).get_hosts(host)
../../../../.venvs/ansible-aws-ena/lib/python2.7/site-packages/testinfra/utils/ansible_runner.py:150: in __init__
    self.variable_manager = ansible.vars.VariableManager()
E   AttributeError: 'module' object has no attribute 'VariableManager'
=============================== warnings summary ===============================
None
  Module already imported so cannot be rewritten: testinfra

-- Docs: http://doc.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
===================== 1 warnings, 1 error in 1.62 seconds ======================
ERROR: 

  RAN: /Users/tnation/.venvs/ansible-aws-ena/bin/testinfra tests/test_ena.py --connection=ansible --ansible-inventory=.molecule/ansible_inventory

  STDOUT:


  STDERR:
```

It worked with Testinfra 1.7.1 (although i did see some deprecation warnings), so I think we should pin that version here.

Comment (hectcastro) [reply requirements.txt]: Looks like I had success with TI 1.6.3, but pinned to the most recent version regardless.
